// <auto-generated />
using EmployeeManagementMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608140514_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementMVC.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "admin@company.com",
                            Password = "admin123",
                            Username = "admin"
                        },
                        new
                        {
                            AdminId = 2,
                            Email = "manager@company.com",
                            Password = "manager123",
                            Username = "manager"
                        });
                });

            modelBuilder.Entity("EmployeeManagementMVC.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Navid",
                            LastName = "Munshi",
                            Position = "Software Engineer",
                            Salary = 75000.00m
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Rafiq",
                            LastName = "Ahmed",
                            Position = "Project Manager",
                            Salary = 95000.00m
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Fatima",
                            LastName = "Rahman",
                            Position = "UI/UX Designer",
                            Salary = 65000.00m
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Kamal",
                            LastName = "Hossain",
                            Position = "Database Administrator",
                            Salary = 80000.00m
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Nusrat",
                            LastName = "Jahan",
                            Position = "QA Engineer",
                            Salary = 60000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
